---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    - stage: "Additional Tests"
      name: "FalTest"
      services: xvfb
      env:
      - WEBDRIVER_BROWSER=firefox
      - DEBUG=@faltest/*
      - WEBDRIVER_DISABLE_CLEANUP=true
      - NETLIFY=false
      script: percy exec -- npm run faltest

    - if: branch = master AND type = pull_request
      name: ember-cli-update
      script:
        - git checkout $TRAVIS_PULL_REQUEST_SHA
        - git checkout -B $TRAVIS_PULL_REQUEST_BRANCH
        - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_PULL_REQUEST_SLUG.git
        - npx https://github.com/kellyselden/ember-cli-update-action.git#semver:^1.5.4 --pull-request-url https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST --autofix-command "npm run lint:js -- --fix"

    - if: tag IS present
      stage: Deploy
      name: "Deploy"
      install: ignore
      script: ignore
      deploy:
        provider: npm
        email: kellyselden@gmail.com
        api_key: $NPM_TOKEN
        edge: true # opt in to dpl v2
        on:
          tags: true
          repo: ember-vr/ember-aframe-shim

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
