---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=aframe-0.5
    - env: EMBER_TRY_SCENARIO=aframe-0.6
    - env: EMBER_TRY_SCENARIO=aframe-0.7
    - env: EMBER_TRY_SCENARIO=aframe-0.8
    - env: EMBER_TRY_SCENARIO=aframe-0.9

    - name: "Node Tests"
      script: npm run nodetest

    - name: "FalTest"
      services: xvfb
      env: WEBDRIVER_BROWSER=firefox
      script: percy exec -- npm run faltest

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
